package com.folium.reader.core.pdf

import java.io.Closeable
import java.util.PriorityQueue
import java.util.concurrent.LinkedBlockingQueue
import java.util.concurrent.ThreadFactory
import java.util.concurrent.ThreadPoolExecutor
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicLong

/**
 * Priority classes for viewport-driven render requests, ordered from highest to lowest.
 *
 * Visible pages always outrank near/prefetch pages, and every reading-path priority
 * outranks OCR, which only ever runs opportunistically once nothing else is pending.
 */
enum class RenderPriority { VISIBLE, NEAR, PREFETCH, OCR }

/** Why a request never produced a published render. */
enum class RejectionReason { STALE_GENERATION, CANCELLED, FAILED }

/**
 * Immutable, engine-neutral description of a single page render, tagged with its submission
 * generation.
 *
 * [token] is supplied by the caller of [ViewportScheduler.submit], not generated by the
 * scheduler, and is carried unchanged onto every [SchedulerOutcome] this request ever produces —
 * a [SchedulerOutcome.Rendered], any [SchedulerOutcome.Rejected] reason, and the backlog
 * settlement [SchedulerOutcome.Rejected] a caller never directly requested (see
 * `folium/scheduler-retryable-contract`). A caller that needs to recognize its own outcome can
 * therefore mint the token before calling [ViewportScheduler.submit] and match on it later,
 * without depending on the returned [RenderHandle] having been recorded first — see
 * [ViewportScheduler.submit]'s own doc for why that ordering matters.
 */
data class ViewportRenderRequest(
    val requestId: Long,
    val pageIndex: Int,
    val priority: RenderPriority,
    val generation: Long,
    val spec: RenderSpec,
    val token: Long = 0L
) {
    init { require(pageIndex >= 0) }
}

/** Result of scheduling a single request: either a published value, or a typed rejection. */
sealed class SchedulerOutcome<out T> {
    data class Rendered<T>(val request: ViewportRenderRequest, val value: T) : SchedulerOutcome<T>()

    /**
     * [failure] carries the original [PdfFailure] taxonomy when [reason] is [RejectionReason.FAILED],
     * so a consumer can distinguish a retryable resource failure from a terminal one. It is always
     * null for [RejectionReason.STALE_GENERATION] and [RejectionReason.CANCELLED].
     */
    data class Rejected(
        val request: ViewportRenderRequest,
        val reason: RejectionReason,
        val failure: PdfFailure? = null
    ) : SchedulerOutcome<Nothing>()
}

/**
 * Produces a render result for a single request, cooperatively honoring [cancellationSignal].
 *
 * Ownership of the returned candidate is transferred to the scheduler: it is either handed to
 * the outcome consumer (on publication) or released (on rejection), exactly once either way.
 */
fun interface ViewportRenderer<T> {
    fun render(request: ViewportRenderRequest, cancellationSignal: CancellationSignal): RenderCandidate<T>
}

/** Opaque token returned by [ViewportScheduler.submit], usable to cancel that specific request. */
class RenderHandle internal constructor(internal val requestId: Long)

/**
 * Thrown by [ViewportScheduler.close] when one or more worker threads have not finished
 * publishing their outcome and releasing their candidate within the scheduler's configured drain
 * timeout. [close] never tears down silently on timeout: [ViewportScheduler] is already marked
 * closed and every queued request already rejected by the time this is thrown, but
 * [stillDrainingCount] of the [totalAwaitingDrain] worker threads that were awaiting drain may
 * still be running their consumer callback or candidate release, so any guarantee that depends on
 * a full drain — no leaked render handle, no outstanding outcome delivery — does not hold until
 * those threads actually finish on their own.
 */
class SchedulerCloseTimeoutException(
    val stillDrainingCount: Int,
    val totalAwaitingDrain: Int
) : IllegalStateException(
    "ViewportScheduler.close() timed out waiting for $stillDrainingCount of $totalAwaitingDrain " +
        "worker task(s) to finish publishing outcomes and releasing candidates"
)

/**
 * Thrown by [ViewportScheduler.submit] once [ViewportScheduler.close] has already run: a closed
 * scheduler accepts no further work, and this is the verified, unchanged invariant behind that
 * refusal. A dedicated subclass of [IllegalStateException], rather than a bare one carrying just a
 * message, so a caller that must react specifically to *this* rejection — as opposed to some other
 * [IllegalStateException] a misbehaving renderer or consumer callback might throw — can catch it by
 * type instead of matching against a message string, while every existing caller that only checks
 * for [IllegalStateException] keeps seeing one.
 */
class SchedulerClosedException : IllegalStateException("ViewportScheduler is closed")

/**
 * Schedules viewport-driven page renders against a bounded worker pool.
 *
 * Requests are immutable and engine-neutral: this class knows nothing about any concrete rendering
 * engine, only the [ViewportRenderer] abstraction. At most [maxConcurrentWorkers] requests are
 * ever dispatched to the renderer — i.e. running [ViewportRenderer.render] — at once; the rest
 * wait in a priority queue ordered by [RenderPriority] and, within a priority, by submission
 * order. This bound covers only the renderer call itself: [onOutcome] delivery and candidate
 * release happen after a worker's dispatch slot has already been freed (see
 * [tasksAwaitingDrain]), so [onOutcome] can be invoked concurrently, from as many distinct threads
 * as the worker pool has, and is not itself limited by [maxConcurrentWorkers]. A consumer that must
 * serialize its own state across outcomes is responsible for its own synchronization.
 *
 * The pool is fixed at [maxConcurrentWorkers] threads and belongs to this instance alone, so two
 * schedulers never contend for each other's capacity. Its threads are created lazily on first
 * dispatch and reused for every request afterwards: [submit] therefore does no thread creation on
 * the calling thread past the first [maxConcurrentWorkers] dispatches, which is what makes it safe
 * to call at gesture-sample rate from a UI thread.
 *
 * Every request is tagged with the generation active when it was submitted. When the generation
 * advances via [advanceGeneration], any request from a superseded generation is rejected with
 * [RejectionReason.STALE_GENERATION] and its candidate released, whether it was still queued or
 * already in flight. [cancel] and [cancelAll] behave the same way for [RejectionReason.CANCELLED].
 *
 * [close] cancels everything outstanding and blocks until every dispatched request other than the
 * one running on the calling thread has published its outcome and released its candidate — so,
 * provided [close] returns rather than throwing [SchedulerCloseTimeoutException] (see below), no
 * render handle or outcome delivery can leak past the call — with one necessary exception: a worker
 * whose own outcome callback reentrantly calls [close] cannot wait for itself, since it is by
 * definition still running that callback. Because release now happens after publication (see
 * [tasksAwaitingDrain]'s KDoc), a consumer's [onOutcome] callback can observe a *rejected*
 * outcome before that request's candidate has actually been released; only [close] returning
 * gives the stricter guarantee that release has already happened too.
 *
 * [close] bounds its drain on [closeDrainTimeoutMillis] and throws [SchedulerCloseTimeoutException]
 * if it expires: any thread still holding a lock that an outcome callback needs — including a
 * callback that itself, non-reentrantly, calls [close] while holding such a lock — would otherwise
 * make [close] hang forever, since a worker cannot finish publishing until that lock is free.
 *
 * [close] is a blocking call and must never be invoked from the Android main thread: even
 * [DEFAULT_CLOSE_DRAIN_TIMEOUT_MILLIS] is long enough to freeze the UI unacceptably on its own,
 * and stacked on top of whatever main-thread work already preceded the call, it can still push the
 * total block past Android's ~5 s ANR input-dispatch threshold. Call it from a background thread,
 * and treat the exception as retryable once the offending lock is free.
 */
class ViewportScheduler<T>(
    private val maxConcurrentWorkers: Int,
    private val renderer: ViewportRenderer<T>,
    private val closeDrainTimeoutMillis: Long = DEFAULT_CLOSE_DRAIN_TIMEOUT_MILLIS,
    private val workerPoolName: String = DEFAULT_WORKER_POOL_NAME,
    private val onOutcome: (SchedulerOutcome<T>) -> Unit
) : Closeable {

    init { require(maxConcurrentWorkers >= 1) }

    companion object {
        /**
         * Chosen well inside Android's ~5 s ANR input-dispatch threshold: even if [close] is
         * mistakenly called from the main thread, a caller sees a diagnosable
         * [SchedulerCloseTimeoutException] instead of the system silently escalating to an ANR. A
         * well-behaved consumer callback that returns promptly drains in milliseconds regardless,
         * so this bound only matters when something is already stuck.
         */
        const val DEFAULT_CLOSE_DRAIN_TIMEOUT_MILLIS: Long = 3_000L

        /**
         * Used by every caller that runs a single scheduler and therefore has nothing to tell apart.
         * A process running several at once should name each one, since the worker thread counter is
         * per-instance and two unnamed schedulers would otherwise both produce `viewport-render-1`.
         */
        const val DEFAULT_WORKER_POOL_NAME: String = "render"
    }

    /**
     * Typed as [java.lang.Object] rather than [Any] purely so [close] can wait on this same monitor
     * for the drain to complete, and a finishing worker can signal it — Kotlin only exposes
     * `wait`/`notifyAll` on that static type. Every critical section in this class is otherwise an
     * ordinary `synchronized(lock)` block.
     */
    private val lock = Object()
    private val nextRequestId = AtomicLong(0)
    private val nextSequence = AtomicLong(0)
    private val nextWorkerThreadId = AtomicLong(0)
    private val pending = PriorityQueue<QueuedRequest>()
    private val inFlight = mutableMapOf<Long, ViewportRenderRequest>()
    private val cancelledIds = mutableSetOf<Long>()

    /**
     * Threads are named after the pool they belong to rather than after any single request, since a
     * pooled thread serves many: `viewport-render-1` is a worker, not a page. [workerPoolName] is
     * what makes a thread attributable to a specific scheduler in a trace: the counter behind the
     * name is per-instance, so without it every scheduler in the process numbers its own threads
     * from 1 and a stack dump cannot say which one a worker belongs to. They are daemon threads so a
     * worker wedged inside a misbehaving renderer or consumer callback can never keep the process
     * alive on its own after [close] has already given up waiting for it.
     */
    private val workerPool = ThreadPoolExecutor(
        maxConcurrentWorkers,
        maxConcurrentWorkers,
        0L,
        TimeUnit.MILLISECONDS,
        LinkedBlockingQueue(),
        ThreadFactory { runnable ->
            Thread(runnable, "viewport-$workerPoolName-${nextWorkerThreadId.incrementAndGet()}").apply { isDaemon = true }
        }
    )

    /**
     * How many requests currently hold a dispatch slot — the bound [dispatchLocked] enforces. A
     * request occupies a slot for the *duration of its dispatch bound*, not for its whole lifetime:
     * [finishWorkerLocked] gives the slot back as soon as the request is decided, so
     * [dispatchLocked] can immediately dispatch replacement work while the outgoing request's
     * outcome is still being published. [close] must not wait on this count — it would ignore a
     * request that has already been decided but whose outcome has not yet been published, which is
     * exactly the defect this class exists to avoid.
     */
    private var dispatchedWorkerCount = 0

    /**
     * The wait set for [close], keyed by request id: a task stays here from the moment it is handed
     * to [workerPool] until it has finished publishing its outcome and releasing its candidate, in a
     * `finally` block that runs after — never inside — the monitor. This is what lets [close]
     * guarantee full drain without waiting on a task while that task still holds [lock].
     *
     * Deliberately separate from [dispatchedWorkerCount], and deliberately not a set of threads: a
     * pooled thread outlives the request it is running, and an entry can exist here before any
     * thread has picked the task up at all. [RenderTask.runningThread] is what identifies the thread
     * currently serving an entry, and is null for an entry still queued inside [workerPool] — which
     * is why [close] evicts those directly (see [cancelDispatchedButUnstartedLocked]) instead of
     * waiting for a pool thread that may itself be the caller.
     *
     * This map's size is bounded by [maxConcurrentWorkers], since an entry is only ever added while
     * holding a dispatch slot.
     */
    private val tasksAwaitingDrain = mutableMapOf<Long, RenderTask>()

    private var currentGeneration = 0L
    private var closed = false

    fun generation(): Long = synchronized(lock) { currentGeneration }

    fun pendingCount(): Int = synchronized(lock) { pending.size }

    /** Test-observable size of the cancellation-suppression set, exposed to assert its bound holds. */
    internal fun cancelledCount(): Int = synchronized(lock) { cancelledIds.size }

    /**
     * Test-observable size of [tasksAwaitingDrain]. A pooled worker thread does not die when its
     * request is done, so a test can no longer prove a worker finished by joining its thread; this
     * is the equivalent observation, and reaching zero means every dispatched request has published
     * its outcome and released its candidate.
     */
    internal fun drainingCount(): Int = synchronized(lock) { tasksAwaitingDrain.size }

    /**
     * Test-only seam letting a unit test force [startWorkerLocked]'s dispatch to fail
     * deterministically, so the rollback path it guards can be covered without relying on genuine
     * native-thread exhaustion or on filling a bounded queue. Throwing from this hook is
     * indistinguishable, to everything downstream, from [ThreadPoolExecutor.execute] itself
     * throwing — which it really can do, either as a [java.util.concurrent.RejectedExecutionException]
     * or by propagating a failure to create one of the pool's own threads. Left `null` in
     * production, where dispatch always goes straight to [workerPool].
     */
    internal var workerDispatchHookForTests: (() -> Unit)? = null

    fun advanceGeneration(): Long {
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        val newGeneration = synchronized(lock) {
            currentGeneration++
            rejectStaleQueuedLocked(toPublish)
            currentGeneration
        }
        publish(toPublish)
        return newGeneration
    }

    /**
     * [token] defaults to `0L` for a caller with no correlation need of its own (every direct
     * scheduler test in this module submits this way). A caller that must recognize its own
     * request against a synchronous outcome — see this class's own doc on synchronous delivery,
     * and [ViewportRenderRequest.token]'s doc — should mint a token before calling this method and
     * pass it here; it is carried, unchanged, onto every [SchedulerOutcome] this request produces.
     *
     * The `0L` default is only safe because this scheduler trusts its token-minting caller to
     * never mint `0L` itself: [HorizontalViewportRequestCoordinator], the only caller that
     * currently supplies a token, mints from an `AtomicLong` starting at `0` and always calling
     * `incrementAndGet()` first, so its first token is `1` and it can never collide with an
     * un-tokened caller's default. This scheduler does not enforce that on its own — a caller that
     * mints from `0` would defeat it. A single [ViewportScheduler] instance is also designed around
     * exactly one `onOutcome` consumer (see this class's own doc), so it is not supported for two
     * [HorizontalViewportRequestCoordinator] instances, each minting its own token sequence from
     * `1`, to share one scheduler: their sequences could collide.
     */
    fun submit(pageIndex: Int, priority: RenderPriority, spec: RenderSpec, token: Long = 0L): RenderHandle {
        val request: ViewportRenderRequest
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        synchronized(lock) {
            if (closed) throw SchedulerClosedException()
            request = ViewportRenderRequest(nextRequestId.incrementAndGet(), pageIndex, priority, currentGeneration, spec, token)
            pending.add(QueuedRequest(request, nextSequence.incrementAndGet()))
            dispatchLocked(toPublish)
        }
        publish(toPublish)
        return RenderHandle(request.requestId)
    }

    /**
     * A cancelled id only needs to live in [cancelledIds] long enough to suppress the outcome it
     * belongs to. A still-queued request is resolved synchronously right here, so its id is never
     * added at all; an in-flight request's id is added now and pruned by [finishWorkerLocked] once
     * that work reports, keeping the set bounded by the number of in-flight requests rather than by
     * the lifetime of the scheduler.
     */
    fun cancel(handle: RenderHandle) {
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        synchronized(lock) {
            val queuedMatch = pending.firstOrNull { it.request.requestId == handle.requestId }
            if (queuedMatch != null) {
                pending.remove(queuedMatch)
                toPublish.add(SchedulerOutcome.Rejected(queuedMatch.request, RejectionReason.CANCELLED))
            } else if (handle.requestId in inFlight) {
                cancelledIds.add(handle.requestId)
            }
        }
        publish(toPublish)
    }

    fun cancelAll() {
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        synchronized(lock) {
            while (pending.isNotEmpty()) {
                val queued = pending.poll()!!
                toPublish.add(SchedulerOutcome.Rejected(queued.request, RejectionReason.CANCELLED))
            }
            cancelledIds.addAll(inFlight.keys)
        }
        publish(toPublish)
    }

    override fun close() {
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        val tasksToDrain: List<RenderTask>
        synchronized(lock) {
            closed = true
            while (pending.isNotEmpty()) {
                val queued = pending.poll()!!
                toPublish.add(SchedulerOutcome.Rejected(queued.request, RejectionReason.CANCELLED))
            }
            cancelledIds.addAll(inFlight.keys)
            cancelDispatchedButUnstartedLocked(toPublish)
            // Excludes the task running on the calling thread so a consumer callback that reenters
            // close() from the worker thread which produced its own outcome cannot deadlock by
            // waiting for itself.
            tasksToDrain = tasksAwaitingDrain.values.filter { it.runningThread !== Thread.currentThread() }
        }
        // A plain try/finally would let a SchedulerCloseTimeoutException thrown while joining
        // silently replace a genuine consumer exception thrown by publish -- the JVM discards a
        // try block's exception when its finally block also throws. Captured here and attached as
        // a suppressed exception instead, mirroring publish's own per-outcome contract.
        var publishError: Throwable? = null
        try {
            publish(toPublish)
        } catch (error: Throwable) {
            publishError = error
        }
        try {
            awaitDrainWithTimeout(tasksToDrain)
        } catch (timeoutError: Throwable) {
            publishError?.let { timeoutError.addSuppressed(it) }
            throw timeoutError
        } finally {
            // Runs even on timeout: a pool whose threads are wedged must still be told to retire
            // them once they do finish, or a scheduler that failed to drain leaks its whole pool.
            // shutdown() never interrupts a running task, so it cannot truncate a drain in progress.
            workerPool.shutdown()
        }
        publishError?.let { throw it }
    }

    /**
     * Evicts every request that has been dispatched but that no pool thread has picked up yet, and
     * settles it here instead. Without this, [close] called from a pool thread — the reentrant case
     * [close]'s own doc describes — could be waiting for a task that cannot start until the caller
     * itself returns its thread to the pool, which only happens after [close] returns. Evicting
     * removes that cycle entirely rather than relying on the drain timeout to break it.
     *
     * [ThreadPoolExecutor.remove] returning true is the proof that eviction is safe: a task still in
     * the pool's queue has demonstrably not been handed to any thread, so it will never run and must
     * be settled here. Returning false is *not* proof of the opposite, and covers two different
     * states, both of which are correctly left in [tasksAwaitingDrain] to be waited for normally:
     * a task some thread has already taken off the queue, and a task that never entered the queue at
     * all, because [ThreadPoolExecutor.execute] ran while the pool was still below its core size and
     * handed it straight to a freshly created worker as that worker's first task. The second case
     * cannot deadlock the reentrant [close] this method exists to protect: such a task owns a brand
     * new thread of its own, so it can never be waiting for the closing caller to give its thread
     * back to the pool.
     */
    private fun cancelDispatchedButUnstartedLocked(toPublish: MutableList<SchedulerOutcome<T>>) {
        val unstarted = tasksAwaitingDrain.values.filter { it.runningThread == null }
        for (task in unstarted) {
            if (!workerPool.remove(task)) continue

            val request = task.request
            tasksAwaitingDrain.remove(request.requestId)
            inFlight.remove(request.requestId)
            cancelledIds.remove(request.requestId)
            dispatchedWorkerCount--

            toPublish.add(SchedulerOutcome.Rejected(request, RejectionReason.CANCELLED))
        }
    }

    /**
     * Bounds the drain so a worker that can never finish — e.g. its outcome callback is blocked on a
     * lock some other thread holds while calling [close] — cannot hang [close] forever. The deadline
     * is shared across all of [tasksToDrain] rather than applied per task, so a slow first worker
     * cannot starve the timeout budget for the rest.
     *
     * Waits on [lock] rather than joining threads: a pooled thread does not die when its request is
     * done, so thread liveness says nothing about whether an outcome has been published. Each task
     * removes its own entry and signals this monitor once it has genuinely finished.
     */
    private fun awaitDrainWithTimeout(tasksToDrain: List<RenderTask>) {
        if (tasksToDrain.isEmpty()) return

        val idsToDrain = tasksToDrain.map { it.request.requestId }
        val deadlineNanos = System.nanoTime() + TimeUnit.MILLISECONDS.toNanos(closeDrainTimeoutMillis)
        var stillDraining = 0
        synchronized(lock) {
            while (true) {
                stillDraining = idsToDrain.count { it in tasksAwaitingDrain }
                if (stillDraining == 0) return

                val remainingNanos = deadlineNanos - System.nanoTime()
                if (remainingNanos <= 0) break
                lock.wait(TimeUnit.NANOSECONDS.toMillis(remainingNanos).coerceAtLeast(1))
            }
        }
        throw SchedulerCloseTimeoutException(stillDraining, tasksToDrain.size)
    }

    private fun rejectStaleQueuedLocked(toPublish: MutableList<SchedulerOutcome<T>>) {
        val stale = pending.filter { it.request.generation != currentGeneration }
        stale.forEach { queued ->
            pending.remove(queued)
            toPublish.add(SchedulerOutcome.Rejected(queued.request, RejectionReason.STALE_GENERATION))
        }
    }

    /**
     * Stops attempting further dispatches after the first failure rather than retrying the rest of
     * the backlog synchronously under [lock]: under sustained memory pressure, every further
     * attempt in this same call would likely also fail, and a dispatch that has to materialize one
     * of the pool's own threads is not guaranteed to be cheap. A closed loop that simply returned at that point,
     * however, leaves whatever is left in [pending] with no internal trigger to ever try again: the
     * only two callers of this method are [submit] and [finishWorkerLocked], and once every live
     * worker has finished, neither fires again on its own. So instead of stopping the loop outright,
     * [drainRemainingAsFailedLocked] resolves everything still queued with the same typed, retryable
     * rejection this method already uses for the request whose start failed, at zero further thread
     * creation cost. This intentionally settles every remaining priority uniformly rather than
     * letting a lower-priority request quietly survive in [pending] while a higher-priority one is
     * the one sacrificed by the failed start.
     */
    private fun dispatchLocked(toPublish: MutableList<SchedulerOutcome<T>>) {
        while (dispatchedWorkerCount < maxConcurrentWorkers) {
            val queued = pending.poll() ?: return

            if (isSupersededLocked(queued.request)) {
                toPublish.add(SchedulerOutcome.Rejected(queued.request, rejectionReasonLocked(queued.request)))
                continue
            }

            if (!startWorkerLocked(queued.request, toPublish)) {
                drainRemainingAsFailedLocked(toPublish)
                return
            }
        }
    }

    private fun drainRemainingAsFailedLocked(toPublish: MutableList<SchedulerOutcome<T>>) {
        while (pending.isNotEmpty()) {
            val queued = pending.poll()!!
            if (isSupersededLocked(queued.request)) {
                toPublish.add(SchedulerOutcome.Rejected(queued.request, rejectionReasonLocked(queued.request)))
            } else {
                toPublish.add(SchedulerOutcome.Rejected(queued.request, RejectionReason.FAILED, PdfFailure.Resource(retryable = true)))
            }
        }
    }

    /**
     * Dispatch failing must never propagate out of here: this is called from [dispatchLocked],
     * which is itself called from inside [finishWorkerLocked] while a *different* worker's own
     * outcome and candidate are still waiting, further up the same call stack, to be published and
     * released by [runWork]. An uncaught throw here would unwind past both, losing that other
     * worker's already-decided result. On failure every mutation made just above is rolled back so
     * the dispatch slot is not permanently burned, and the request itself is surfaced as a typed,
     * retryable rejection rather than silently stranded. Returns whether the request was actually
     * handed to [workerPool], so [dispatchLocked] knows to stop attempting further dispatches and
     * drain the rest of the backlog instead.
     *
     * [Throwable] rather than a narrower type is caught on purpose: the pool refuses work with a
     * [java.util.concurrent.RejectedExecutionException], but materializing one of its own threads
     * can still fail the way an explicit [Thread.start] used to (the OS refusing to create a native
     * thread under memory pressure), which surfaces as an [Error]. Both must take this same
     * rollback path and produce the same typed outcome.
     *
     * [workerDispatchHookForTests], when non-null, runs immediately before the dispatch below so a
     * unit test can force this failure branch deterministically, without any production caller ever
     * being able to observe or set it.
     */
    private fun startWorkerLocked(request: ViewportRenderRequest, toPublish: MutableList<SchedulerOutcome<T>>): Boolean {
        inFlight[request.requestId] = request
        val task = RenderTask(request)
        dispatchedWorkerCount++
        tasksAwaitingDrain[request.requestId] = task
        try {
            workerDispatchHookForTests?.invoke()
            workerPool.execute(task)
        } catch (failure: Throwable) {
            dispatchedWorkerCount--
            tasksAwaitingDrain.remove(request.requestId)
            inFlight.remove(request.requestId)
            toPublish.add(SchedulerOutcome.Rejected(request, RejectionReason.FAILED, PdfFailure.Resource(retryable = true)))
            return false
        }
        return true
    }

    /**
     * Owns the two things a per-request thread used to carry implicitly: which thread is currently
     * serving this request (so [close] can exclude a reentrant caller and evict what has not
     * started), and when the request has truly finished. Its entry in [tasksAwaitingDrain] is
     * removed only after [runWork] has published and released, and the removal signals [lock] so a
     * waiting [close] wakes immediately rather than on its timeout.
     */
    private inner class RenderTask(val request: ViewportRenderRequest) : Runnable {
        @Volatile var runningThread: Thread? = null

        override fun run() {
            runningThread = Thread.currentThread()
            try {
                runWork(request)
            } finally {
                synchronized(lock) {
                    tasksAwaitingDrain.remove(request.requestId)
                    lock.notifyAll()
                }
            }
        }
    }

    private fun runWork(request: ViewportRenderRequest) {
        val cancellationSignal = CancellationSignal { synchronized(lock) { isSupersededLocked(request) } }

        val candidate = try {
            renderer.render(request, cancellationSignal)
        } catch (failure: PdfException) {
            finishFailedWorkerAndPublish(request, failure.failure)
            return
        } catch (unexpected: Throwable) {
            finishFailedWorkerAndPublish(request, PdfFailure.Resource(retryable = false))
            return
        }

        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        var releaseCandidate = false
        synchronized(lock) {
            if (isSupersededLocked(request)) {
                releaseCandidate = true
                toPublish.add(SchedulerOutcome.Rejected(request, rejectionReasonLocked(request)))
            } else {
                toPublish.add(SchedulerOutcome.Rendered(request, candidate.value))
            }
            finishWorkerLocked(request, toPublish)
        }
        try {
            publish(toPublish)
        } finally {
            if (releaseCandidate) candidate.release()
        }
    }

    private fun finishFailedWorkerAndPublish(request: ViewportRenderRequest, failure: PdfFailure) {
        val toPublish = mutableListOf<SchedulerOutcome<T>>()
        synchronized(lock) {
            toPublish.add(SchedulerOutcome.Rejected(request, RejectionReason.FAILED, failure))
            finishWorkerLocked(request, toPublish)
        }
        publish(toPublish)
    }

    /**
     * Frees the dispatch slot immediately so [dispatchLocked] can start replacement work on a
     * freed worker count, without waiting for this request's outcome to be published or its
     * candidate released — those happen after the caller leaves this critical section. The
     * corresponding [tasksAwaitingDrain] entry is removed separately, only once publication and
     * release are done, so [close] keeps waiting for this request until it has truly finished.
     */
    private fun finishWorkerLocked(request: ViewportRenderRequest, toPublish: MutableList<SchedulerOutcome<T>>) {
        inFlight.remove(request.requestId)
        cancelledIds.remove(request.requestId)
        dispatchedWorkerCount--
        dispatchLocked(toPublish)
    }

    private fun isSupersededLocked(request: ViewportRenderRequest): Boolean =
        request.generation != currentGeneration || request.requestId in cancelledIds

    private fun rejectionReasonLocked(request: ViewportRenderRequest): RejectionReason =
        if (request.requestId in cancelledIds) RejectionReason.CANCELLED else RejectionReason.STALE_GENERATION

    /**
     * Every outcome in [outcomes] was already decided under [lock] before being collected here;
     * delivering it after the lock is released does not reopen that decision, since the request
     * was atomically removed from [pending]/[inFlight] in the same critical section that produced
     * it, so no other call can resolve it a second time. Publishing outside the monitor keeps a
     * slow or reentrant consumer from stalling [cancel]/[cancellationSignal] polling for unrelated
     * in-flight work, and keeps [close] from joining a worker thread while that thread is blocked
     * waiting on its own callback.
     *
     * Each outcome is delivered independently: a callback throwing for one outcome must not
     * prevent delivery of the others in the same batch, since [dispatchLocked] can append other,
     * already-dequeued requests' rejections into the same list a worker's own outcome travels in.
     * The first captured failure (with any further ones attached as suppressed) is rethrown after
     * every outcome has been attempted, so a misbehaving callback is still surfaced rather than
     * silently swallowed.
     */
    private fun publish(outcomes: List<SchedulerOutcome<T>>) {
        var firstError: Throwable? = null
        for (outcome in outcomes) {
            try {
                onOutcome(outcome)
            } catch (error: Throwable) {
                if (firstError == null) firstError = error else firstError.addSuppressed(error)
            }
        }
        firstError?.let { throw it }
    }

    private class QueuedRequest(val request: ViewportRenderRequest, val sequence: Long) : Comparable<QueuedRequest> {
        override fun compareTo(other: QueuedRequest): Int {
            val byPriority = request.priority.ordinal.compareTo(other.request.priority.ordinal)
            return if (byPriority != 0) byPriority else sequence.compareTo(other.sequence)
        }
    }
}
